### ISSUE TITLE
How can i have one global persistent store for all widgets/screens?

### ISSUE THREAD

**Issue by dukaric1991** [mobxjs/mobx.dart#128]
How can i have one global persistent store for all widgets/screens, which are generated trough navigator. I would like to set some store value "X=5" in first screen and then go to next screen with navigator, and i would like to access to this store X value/observable and change it to "X=6"some new value, and when i go back to first screen the X value would be changed to 6?

**Comment by Rahiche** [comment]
you just have to make the store at the root of your widgets tree using an inherited widget and access it from the children.
one easy way to do is through a generic provider like [Provider ](https://github.com/rrousselGit/provider)
```
Provider<MyStore>(
  value: MyStore(),
  child: // Your App 
)
```

**Comment by dukaric1991** [comment]
I tried, and when i go to another screen with Navigator.of(context).pushAndRemoveUntil('/screen2) i get the error: 
Error: Could not find the correct Provider<MobxStore> above this WelcomeWidget Widget 
I/flutter ( 3456): 
I/flutter ( 3456): To fix, please:
I/flutter ( 3456): 
I/flutter ( 3456):   * Ensure the Provider<MobxStore> is an ancestor to this WelcomeWidget Widget 
I/flutter ( 3456):   * Provide types to Provider<MobxStore>
I/flutter ( 3456):   * Provide types to Consumer<MobxStore>
I/flutter ( 3456):   * Provide types to Provider.of<MobxStore>()
I/flutter ( 3456):   * Always use package imports. Ex: `import 'package:my_app/my_code.dart';
I/flutter ( 3456):   * Ensure the correct `context` is being used.

**Comment by pavanpodila** [comment]
@dukaric1991 I just pushed an example called **multi_counter**, which employs the concept of `Provider` and a global store that spans across pages.

Please take a look [here](https://github.com/mobxjs/mobx.dart/tree/master/mobx_examples/lib/multi_counter).

**Comment by CalebJTSmith** [comment]
I was trying to figure out a way to share it across several different screens for one of my stores and found the best way (so far) using the [get_it package](https://pub.dartlang.org/packages/get_it).

I have a global application class that I use to set my variables I want to use across screens
```
class Application {
  static GetIt getIt;
}
```
then I set info on the main.dart file
```
final getIt = new GetIt();
Dependencies.configureSingletons(getIt);
getIt.registerSingleton<MyModelStore>(MyModelStore());
Application.getIt = getIt;
```
then I can grab it wherever I need it with `final MyModelStore myStore = Application.getIt<MyModelStore>();`

**Comment by rrousselGit** [comment]
> I was trying to figure out a way to share it across several different screens

Why not just wrap your MaterialApp into a provider? 


```dart
StatefulProvider(
  valueBuilder: (context) => MyModelStore(), 
  child: MaterialApp(...)
)
```


This makes the store available for all screens.

**Comment by dukaric1991** [comment]
@rrousselGit And how to access a store value then from any other screen? Do i need to instantiate`final MyModelStore myStore = MyModelStore();` my store in my class/widget and just call it like that: `myStore.someValue`?

**Comment by pavanpodila** [comment]
Sometimes you do need different providers at different levels. They will come and go as necessary according to the lifetime of the view.

I have faced the exception when navigating with a route. @rrousselGit might know better.

**Comment by CalebJTSmith** [comment]
> Why not just wrap your MaterialApp into a provider?

That works too. If you have multiple stores, I find it easier to use the global variable or use your Provider package (did that on another smaller project). I had a global theming store that I wanted to use across all of my screens and `get_it` made that part of it drastically easier for me. But pages that are pretty siloed I will use a `StatefulProvider` since the store is usually contained quite a bit.

**Comment by CalebJTSmith** [comment]
@dukaric1991 - You'll want to reference this for your example: https://pub.dartlang.org/packages/provider#statefulprovider

**Comment by rrousselGit** [comment]
Globals are very bad. They prevent widgets from being customizable/reusable. 

Inheritedwidgets and therefore Provider exists to replace globals

**Comment by dukaric1991** [comment]
But with Provider i have to always pass store trough parameters to new widgets, if i understand correctly?

**Comment by rrousselGit** [comment]
No, simply do:

```
Provider.of<MyStore>(context);
```

**Comment by CalebJTSmith** [comment]
> It's like a global, but with extra perks.

Can you elaborate on this one? I'm still learning so I'd love to have some extra resources on how I can work smarter.

**Comment by dukaric1991** [comment]
@rrousselGit In a new widget i need to declare my new store in build method like this:   
```
@override
  Widget build(BuildContext context) {
      final store = Provider.of<MobxStore>(context);
``` ?

**Comment by rrousselGit** [comment]
Providers, or more broadly InheritedWidgets behaves like globals: They are accessible to all widgets without having to pass them to the constructor of a widget.

But they have other benefits:
- If the value of a provider change, all widgets which depend on the value updates accordingly

- Providers are scoped. Everybody can access to a global, but you can restrict who can access a provider by changing its location in the tree. 

- Having a circular dependency with providers is impossible.

- Since they are scoped, it's possible to locally override provided values (like changing the theme just for a single page).

____

One potential example of their power is a tutorial screen:

Consider two routes:
- Home, showing fancy graphics with real data
- Tutorial, showing something similar to Home, but with mocked data and some overlays

If your Home is implemented using globals – then you'll have a hard time making your tutorial screen. What most peoples end up doing is making the tutorial with an image (duh).

If you're using providers – then you can implement your tutorial by using the actual Home. But by locally overriding the Store, with mock data. That's a lot more effective than a screenshot.

**Comment by CalebJTSmith** [comment]
That was awesome - Thank you for elaborating on that! That makes sense and I can definitely see where that could've been causing some issues in my project. I appreciate laying all of that out there!

**Comment by DoReVo** [comment]
```
ObservableList<dynamic> transaction;

return Provider.value(
      value: transaction,
      child: <someChild>)
```
So I did this on my root widget which is the Home. ```ObservableList<dynamic> transaction;``` is declared outside main. Then I have this child widget below:

```
@override
  Widget build(BuildContext context) {
    final myStore = Provider.of<ObservableList<dynamic>>(context);

    return Observer(
      
      builder: (_) => ListView.separated(
        itemCount: 5,
        shrinkWrap: true,
        itemBuilder:(BuildContext context, int index){
          
          return TransactionItem(myStore[index].id.toString(), myStore[index].getCategory,index);
        },
        separatorBuilder: (BuildContext context, int index) => const Divider()
          
        ,
      ),
    );
  }

```
When i put the observer in this child widget somewhere down the line, it says ```No observables detected in the build method of Observer``` . When i changed the value of the items in my store which is ```ObservableList<dynamic> transaction``` . This child widget does not update its value. So what did i do wrong here that the debugger says ```No observables detected in the build method of Observer``` ?
