### ISSUE TITLE
ObservableFuture state is pending even after future has been completed

### ISSUE THREAD

**Issue by smiLLe** [mobxjs/mobx.dart#238]
Gitter Quote 
>  @pavanpodila i think i run into a weird bug, using the ObservableFuture. if you go to this test: https://github.com/mobxjs/mobx.dart/blob/master/mobx/test/observable_future_test.dart#L17 … remove this three lines
>  ```dart
>        expect(future.status, equals(FutureStatus.pending));
>        expect(future.value, isNull);
>        expect(future.error, isNull);
>  ```
>  
> then the test will fail on line 22. This is because the ObservableFuture still is in pending state. I am experiencing this on my own project. The fix is to call future.status/value/error before the future completes.
>

**Comment by pavanpodila** [comment]
Hi @smiLLe, this is definitely a bug and has to do with the way micro-tasks (Futures are micro-tasks) are handled in the Dart runtime. Also we have made ObservableFuture<T> lazy, which means we don't compute the result/value/status, unless explicitly read. That could be be the reason why the tests are also written that way.

Also would be good to get some insights from @katis

**Comment by smiLLe** [comment]
i tried something and had a code like this (example code):

``` dart
void someFunc() async {
  await load(1);
  await load(2);
}

ObservableFuture _fetch;
Future<void> load(int page) async {
  if (_fetch?.status == FutureStatus.pending) {
    return await _fetch
  }

  final future = http.get(..);
  _fetch = ObservableFuture(fut);
  /// adding _fetch.status here will solve the problem
  await _fetch;
  
  /// _fetch.status is pending without the fix above

  return _fetch;
}
```

**Comment by pavanpodila** [comment]
This has been fixed and pushed to `0.3.5` available on [pub.dev](https://pub.dev/packages/mobx)

**Comment by smiLLe** [comment]
Can confirm. It is working :) Thanks @pavanpodila

**Comment by hmayer00** [comment]
@pavanpodila, I think something might have gone crooked here? If I go to https://pub.dev/packages/mobx, I get:

> Pub is not feeling well #
Fatal package site error.
Please open an issue: https://github.com/dart-lang/pub-dev/issues/new
Add these details to help us fix the issue:Fatal package site error.
Requested URL: https://pub.dev/packages/mobx
Request ID: 3d71dfba07bea4e0eb69c31e3cc4fd6f

I ended up there because I just now added mobx to a brand new project and ended up with build_runner errors. When I dug in to the output and my pubspec.lock, it was using version 0.3.7, but you said above that you just pushed 0.3.5. I'm guessing these two issues are related, but I am super new to flutter and dart and I'm well beyond my ken. When I specified the version 03.5 in pubspec.yaml, everything worked out correctly.

There's a chance that there's just something silly I don't understand going on here, so I didn't feel comfortable opening a new issue for it. But wanted to let you know.

**Comment by hmayer00** [comment]
Actually when I first did that, I could run other searches on pub.dev without getting that error. But now when I check again, all pub.dev searches seem to be going to the same kind of error, so this might have nothing to do with mobx at all. So you might want to just ignore me. If it looks like things are back to normal tomorrow I'll just go ahead and delete these comments so as not to muddy this issue.
