### ISSUE TITLE
Write doc comments for all public API

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx.dart#308]
This needs to be done for:

- [x] mobx
- [x] flutter_mobx
- [ ] mobx_codegen

**Comment by hmayer00** [comment]
I'd also ideally throw flutter_mobx_forms in the mix :)

I'm using mobx (and really stoked about it), but I've been holding off on the `@store` notation and on flutter_mobx_forms, since I've had trouble figuring out how to use those. Any chance docs might come for those things at some point? Sorry I should probably offer to help but I'm not really clear on where to start so doubt I'm qualified. (Though I might have something useful on mobx + graphql at some point once I've worked out some kinks).

Thanks!

**Comment by pavanpodila** [comment]
The `@store` is still experimental and we haven't tested it across all scenarios yet. @shyndman can answer this part better 🙂

**Comment by insinfo** [comment]
how does this flutter_mobx_forms package work? Do you have an example with a user registration form and an example with login form?

**Comment by pavanpodila** [comment]
Sorry that package is not under development right now.
