### ISSUE TITLE
pub conflicts with dart_json_mapper

### ISSUE THREAD

**Issue by felipeleon73** [mobxjs/mobx.dart#341]
I have a pub conflict:
[ApolloXI] flutter packages get
Running "flutter pub get" in ApolloXI...                        
Because dart_json_mapper >=1.2.7 depends on reflectable ^2.2.1 which depends on analyzer ^0.39.0, dart_json_mapper >=1.2.7 requires analyzer ^0.39.0.

And because mobx_codegen >=0.3.10 depends on analyzer >=0.36.3 <0.39.0, dart_json_mapper >=1.2.7 is incompatible with mobx_codegen >=0.3.10.
So, because apolloxi depends on both mobx_codegen 0.3.10+1 and dart_json_mapper >=1.2.9, version solving failed.
pub get failed (1; So, because apolloxi depends on both mobx_codegen 0.3.10+1 and dart_json_mapper >=1.2.9, version solving failed.)
exit code 1

is possible to update analyazer version dependency?

**Comment by pavanpodila** [comment]
Let me get to it tomorrow. Away from computer right now

**Comment by pavanpodila** [comment]
@shyndman Can we bump up the upper-limit of the analyzer version?

**Comment by shyndman** [comment]
Sure can. Give me a few.

**Comment by shyndman** [comment]
I pretty much got it, but hit some deprecations. I'm marking them ignored for now, and filing an issue separately to upgrade our analyzer dependency's lower bound at some point so that we can move to the suggested replacements.

Also posted a question to https://github.com/dart-lang/sdk/issues/39943 to understand one of the deprecations, and their deprecation policy.

**Comment by shyndman** [comment]
^ in PR
