### ISSUE TITLE
Add ObservableListofList

### ISSUE THREAD

**Issue by deadsoul44** [mobxjs/mobx.dart#442]
I have a list of list and the UI should be reactive to changes to both inside and outside list. I generate list of list by grouping MyModel list:
```
ObservableList<ObservableList<MyModel>> myModelListGrouped = myModelList
          .asObservable()
          .groupBy((obj) => obj.id)
          .values
          .toList()
          .asObservable();
```

But I get the following exception:
```
type 'ObservableList<List<MyModel>>' is not a subtype of type 'ObservableList<ObservableList<MyModel>>'
```

Is there any workaround or is it possible to add ObservableListOfList.of() functionality to MobX?

**Comment by pavanpodila** [comment]
You will have to rethink this as the use case you are mentioning is specific to your application and not generally applicable. If you apply the Observer to the inner list, it will automatically re-render the UI. 

The reason you are getting the error is because the `.groupBy()` is giving you a plain `List<T>`, instead of `ObservableList<T>`. You will have to break the chain and create the proper Observable collection instead of taking the `List<T>` directly

**Comment by deadsoul44** [comment]
I will try to either use .map or create a custom groupby which will return observable list. Thank you.
