### ISSUE TITLE
Can we put something in the README about error handling?

### ISSUE THREAD

**Issue by tek08** [mobxjs/mobx.dart#540]
Seems like there's a lot of invisible swallowing of errors by mobx reactions, unbeknownst to folk, and not a lot of documentation on such.  It's cost me a couple of hours here and there, and by the look of other issues on here, looks like it is doing the same to others.

Can we ask for a bit of documentation in the README about how errors are captured/handled in reactions, and how to use `disableErrorBoundaries`?

As an example of troublesome code, I've been trying to write a unit test to verify that, when an Observable (one that triggers an async API call) is modified, the resulting API call is run and with the correct arguments.  Something like:

```dart
runSomeTriggerAction(...);
mobx.when((_) => anObservableImpliesASeriesOfActionsHasCompleted(), () { 
  var capturedArg = verify(asyncApiCallOccurred(captureAny)).captured[0];
  expect(capturedArg, someValue);
});
```

or:

```dart
runSomeTriggerAction(...);
mobx.when((_) => anObservableImpliesASeriesOfActionsHasCompleted(), () { 
  var capturedArg = verify(asyncApiCallOccurred(captureAny)).captured[0];
  expect(capturedArg, someValue);
}, onError: (error, rxn) {
  throw error;
});
```

Perhaps I'm not understanding something fundamental about mobx?  How do we write unit tests that need to verify behavior in reactions?

**Comment by MaikuB** [comment]
Hmm I haven't tried using a reaction to as a way to assert. To me it leans more towards testing MobX itself as the test code itself is depending on MobX since it's setting up a reaction. Based on the code snippets you have though, it looks off as you've triggered an action before setting up the reaction as well. In terms of the arrange-act-assert sequence, the code reads as though arrange and assert are happening as the last thing. As such, I would expect the reaction to not even fire if `runSomeTriggerAction(...)` only did synchronous work as the reaction is setup after the method has been executed.

If your reaction invokes some API, testing it shouldn't be different than if MobX wasn't used. That is you'd go from

```
runSomeTriggerAction(...);
mobx.when((_) => anObservableImpliesASeriesOfActionsHasCompleted(), () { 
  var capturedArg = verify(asyncApiCallOccurred(captureAny)).captured[0];
  expect(capturedArg, someValue);
});
```

to something like

```
runSomeTriggerAction(...);
var capturedArg = verify(asyncApiCallOccurred(captureAny)).captured[0];
expect(capturedArg, someValue);
```

Assuming you have a store that defines the action, it could depend on some class (e.g. service as per https://mobx.netlify.app/guides/stores#the-triad-of-widget---store---service) that is responsible for the API call that would be run when the observable is modified. For your test, you'd pass a mock instance of this service to your store to verify that `asyncApiCallOccurred(...)` is invoked. There's probably not much point in having the `expect(...)` code though as your test code would be defining what will happen when `asyncApiCallOccurred(...)` is called (return a result, throw an exception etc)

**Comment by pavanpodila** [comment]
Closing for inaction

**Comment by hacker1024** [comment]
I'd appreciate this as well, I was wondering where my exceptions were going.

Based on #23, it looks like adding this in `main()` should throw all exceptions, but it doesn't seem to be doing so.

```dart
mainContext.onReactionError((error, reaction) {
  throw error;
});
```
