### ISSUE TITLE
do I need dispose after I used Mobx

### ISSUE THREAD

**Issue by DinoDom** [mobxjs/mobx.dart#564]
do I need dispose after I used Mobx?
Something like ScrollController.dispose()

**Comment by avioli** [comment]
Quick answer - yes. Long answer - it depends.

If you are going to create only one instance of something that calls `autorun`, `reaction` or `when` reaction then you don't have to dispose anything, since when your app terminates everything will be disposed off anyway.

But if you are creating many many instances that add any of the above reaction trackers, then you will be constantly allocating memory for them, but not freeing it once your instances get disposed of.

I'm assuming you are using MobX within Flutter, so as per your question - the widget's `dispose` method is the best place to dispose the `ReactionDisposer` instances these methods return, which you probably will create in the widget's `initState` method.

If you are using a `Provider`, then the `dispose` callback is the place you can dispose of your "singleton", but then if you use a provider that is practically never disposed, then there's no real need.

The practice of freeing allocated memory is a good habit to have.

**Comment by DinoDom** [comment]
> `Store` instances don't need to be disposed off. The moment no variable references a Store instance - Dart will (hopefully) release the memory it used.
> 
> On the other hand...
> 
> If you are going to create only one instance of something (say a Widget) that calls `autorun`, `reaction` or `when`º reaction then you don't have to dispose anything, since when your app terminates everything will be disposed off anyway.
> 
> But if you are creating many many instances that add any of the above reaction trackers, then you will be constantly allocating memory for them, but not freeing it once your instances get disposed of.
> 
> I'm assuming you are using MobX within Flutter, so as per your question - the widget's `dispose` method is the best place to dispose the `ReactionDisposer` instances these methods return, which you probably will create in the widget's `initState` method.
> 
> If you are using a `Provider`, then the `dispose` callback is the place you can dispose of your "singleton", but then if you use a provider that is practically never disposed, then there's no real need.
> 
> The practice of freeing allocated memory is a good habit to have.
> 
> º A `when` reaction will auto-dispose itself _when_ the the predicate you provide is met, but if it is never met then it will never be disposed off.

Thanks for your answer. 
But how can,I manualy dispose `Store` in `StatelessWidget`
Such as this:

main_page_store.dart
`import 'package:flutter/material.dart';
import 'package:mobx/mobx.dart';

part 'main_page_store.g.dart';

class MainPageStore = MainPageStoreMobx with _$MainPageStore;

abstract class MainPageStoreMobx with Store {
  @observable
  ScrollController controller;

  @action
  void initController() {
    this.controller = ScrollController();
  }
}`

main_page.dart
`import 'package:flutter/material.dart';

class MainPage extends StatelessWidget {
  final MainPageStore _store = MainPageStore();

  @override
  Widget build(BuildContext context) {
    _store.initController();

    return Observer(
      builder: (_) => SingleChildScrollView(
        controller: _store.controller,
        child: Container(),
      ),
    );
  }
}`

In this case, how can I dispose controller? Will it auto-dispose?

**Comment by avioli** [comment]
That's not the use case of MobX, although you can use it for this. Unfortunately I don't advocate such use, so I won't be showing you how to do it.

Instead I'll try to show you that you should simply use a `StatefulWidget`.

`ScrollController` is a state holder itself - you should use a `StatefulWidget` and keep that instance within its `State` instance.

A `StatelessWidget` shouldn't instantiate a Store like you do in your example (`_store` in your case), since such a widget will be (usually) rebuilt many times. You should use a `StatefulWidget` so you can hold the `_store` instance within its `State` instance.

You should not call effects (which `_store.initController()` does) from within `build` callbacks, unless there is a valid reason for that. This should be called from the `initState` of your `StatefulWidget`.

I hope this makes sense.

**Comment by DinoDom** [comment]
> To answer your question - no - it will not auto-dispose. StatelessWidgets don't hold state and don't offer a way to act upon their disposal.
> 
> Storing a state-holder within a Store is not the use case of MobX, although you can use it for this. Unfortunately I don't advocate such use, so I won't be showing you how to do it.
> 
> Instead I'll try to show you that you should simply use a `StatefulWidget`.
> 
> `ScrollController` is a state holder itself - you should use a `StatefulWidget` and keep that instance within its `State` instance.
> 
> A `StatelessWidget` shouldn't instantiate a Store like you do in your example (`_store` in your case), since such a widget will be (usually) rebuilt many times. You should use a `StatefulWidget` so you can hold the `_store` instance within its `State` instance.
> 
> You should not call effects (which `_store.initController()` does) from within `build` callbacks, unless there is a valid reason for that. This should be called from the `initState` of your `StatefulWidget`.
> 
> I hope this makes sense.
> 
> What is your use case of that MainPageStore? Why do you need to keep a reference of a ScrollController there?
> 
> If you need to be able to scroll it programatically or persist the scroll offset, then I advise you store it globally.
> 
> To transform your `main_page.dart' to use StatefulWidget:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> class MainPage extends StatefulWidget {
>   _MainPageState createState() => _MainPageState();
> }
> 
> class _MainPageState extends State<MainPage> {
>   final MainPageStore _store = MainPageStore()..initController();
> 
>   @override
>   void dispose() {
>     _store.controller.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Observer(
>       builder: (_) => SingleChildScrollView(
>         controller: _store.controller,
>         child: Container(),
>       ),
>     );
>   }
> }
> ```

Thanks for your answer, I know what should I do now
