### ISSUE TITLE
Reaction is not running on objects

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mobxjs/mobx.dart#626]
I have an object called User where I store user data. 

```
@observable
User user;
```

It is used in multiple places using GetIt singletons. I have general app header where i am observing user.name by doing this:

```
    Observer(builder: (_) => Text(userStore.user.name))
```

and I have page with form where I am editting user info. Changing name looks like:

```
    Observer(
              builder: (_) => TextFormField(
                    initialValue: _userStore.user.name,
                    decoration: InputDecoration(
                        labelText: 'Name'),
                    onChanged: (value) => _userStore.user.name = value,
                  ))
```
Header value changes when i change value in input field (not sure how because object refference is not changing - but lets say it is MobX magic :) and mobx runs shallow comparison)

also I am adding reactions on user.name (i tried to add reaction an whole user object too)

```

  void setupValidations() {
    _disposers = [
      reaction((_) => user, validateName1),
      reaction((_) => user.name, validateName2),
      reaction((_) => test, validateName3),
    ];
  }
```

Reaction1 nor Reaction2 are not triggered. However Reaction3 works fine when added on simple observable like: 

```
@observable
String test
```

**Comment by Rudiksz** [comment]
By default Reaction 1 will fire only when you pass a different instance of the User class to your `user` variable, because that's how Dart works with object equality. You can implement == on your class which tell Dart when the to objects are different and mobx will work accordingly. This is standard Dart mechanism, not mobx.


Reaction 2 does not fire because probably your User class is not a Store and its fields are not observables.
If you want to listen to single fields of a class, that too should be a Store with the fields as observables.

**Comment by vytautas-pranskunas-** [comment]
I thought so - but then how user.name in the header refreshes when i change user.name = 'another name'?

**Comment by Rudiksz** [comment]
> I thought so - but then how user.name in the header refreshes when i change user.name = 'another name'?

I don't know. I suspect a parent widget is being rebuilt and it rebuilds your observer too. You would have to check it. Or I'm wrong and mobx listens to non-observable fields too.

> btw - i sthere any MobX helper that converts object to store with nested observables? Because my user class is deserialized from API json. Then this is a general questin how to convert objects comming from API to Observable objects

Not that I know of. I tried to have mobx and json_serializable work together, but gave up on it months ago after I spent countless days of frustrations. I'm happier since, and doing manual serialisation is not a big deal, in spite of the hype around codegen and annotations.

**Comment by vytautas-pranskunas-** [comment]
Whatissues did you have trying mobx and json_serializable work together? Because i have just nigrated from manulau serialization to json_serializable?

**Comment by Rudiksz** [comment]
Something with stores being abstract, it was 6 months ago and it's hazy.  I barely touched my data classes since then, and I don't want another codegen slowing me down.
