### ISSUE TITLE
How to pass a sotre to a child widget

### ISSUE THREAD

**Issue by nicolasvahidzein** [mobxjs/mobx.dart#660]
Hello

I am loading the store in the master widget (a new page loaded via the navigator) using the normal method:

```
	@override
	void didChangeDependencies() {
		super.didChangeDependencies();
		_appStore ??= Provider.of<AppStore>(context, listen: false);
	}
```

so far so good. But i can't remember if i read this somewhere in a tutorial but I am passing the store in a child widget this way:

```
                                return HelpTermsWidget(
					appStore: _appStore,
				);
```

and loading it inside that widget this way:

```
class HelpTermsWidget extends StatelessWidget {
	final AppStore appStore;

	HelpTermsWidget({
		Key key,
		@required this.appStore,
	}) : super(key: key);
	
```

Is this acceptable or it will mess up the store? Not sure if i can ONLY use the didChangeDependencies method in every component even the child one although the parent has the store loaded already.

**Comment by Fleximex** [comment]
I think this is perfectly fine. It will make `HelpTermsWidget` tightly bound to `AppStore` if that's what you want.
In a `StatelessWidget` you don't have the state methods anyway, so those are not an option. The other option would be to call `final _appStore = Provider.of<AppStore>(context, listen: false);` at the top of the `Build` function in `HelpTermsWidget`. This however is not recommended because you want to have as little logic as possible in your `Build` functions.

The common practice to use `didChangeDependencies` is because it is the first lifecycle method where the `BuildContext` is available. If you can pass an instance of the store using dependency injection (passing it with the constructor) you already have your store.

Besides this the MobX documentation notes that using the constructor to passing the store instance is recommended because it makes testing easier. Say you would choose to use `Provider` at the top of the `Build` function to get your store. Providing a mocked version of your store would be a lot more difficult.
https://mobx.netlify.app/guides/stores/#using-proxyprovider-with-a-service

Keep in mind that using `Provider` has the effect that it ensures there is only 1 instance of `AppStore` in the widget tree. In theory `HelpTermsWidget` could receive a copy of AppStore (so not the same `AppStore' instance as the master widget). In practice though, this is extremely unlikely since Dart is pass by reference and not pass by value. And because you use `Provider` as well in the master widget.

One thing however we have not talked about. Why do you need your store in a `StatelessWidget` at all?
Let's say you want a `@observed` `String` from your store for a `Text` widget inside the `HelpTermsWidget`. Passing the store is not necessary. You can just pass the `String` to `HelpTermsWidget` assuming you have `HelpTermsWidget` inside an `Observable` widget in the master widget's build method.

**Comment by nicolasvahidzein** [comment]
@Fleximex thank you so much for your wonderful and helpful answer. I will read what you said in a lot of detail and apply it. Cheers and thanks again.
