### ISSUE TITLE
No observables detected in the build method of Observer when using TextField

### ISSUE THREAD

**Issue by lucasdidur** [mobxjs/mobx.dart#674]
I'm trying to create a form with store, but only in 2 inputs I got this error, and I have no idea why its happens.

```
flutter: No observables detected in the build method of Observer
flutter: #3      _AtualizarCadastroViewAnexoTabState.build          package:flutter_mobx_test/tabs/form_tab1.dart:89
flutter: No observables detected in the build method of Observer
flutter: #3      _AtualizarCadastroViewAnexoTabState.build          package:flutter_mobx_test/tabs/form_tab1.dart:104
```

Here is my source code

https://github.com/lucasdidur/flutter_mobx_test/blob/4c2ecfd6afaff351ec4f15439c02ad5f8ba034bb/lib/tabs/form_tab1.dart#L89

https://github.com/lucasdidur/flutter_mobx_test/blob/4c2ecfd6afaff351ec4f15439c02ad5f8ba034bb/lib/tabs/form_tab1.dart#L104

**Comment by pr-1** [comment]
This is because you are not using any observable to show in the ui. You are updating an observable in onChanged method. For that there is no need of Observer widget.
if we see the docs we should keeep updates inside an action. 
So instead of directly changing the observable from widget . make an action and call that action from the widget.

**Comment by pr-1** [comment]
In other Textfield it is not giving you error because you are showing errorText from store observable.

**Comment by lucasdidur** [comment]
Oh yes, I understand the problem now. Thank you for your help.
