### ISSUE TITLE
Assignation of @observable property not working after 2.1.3+1 !

### ISSUE THREAD

**Issue by ed-oo** [mobxjs/mobx.dart#933]
Hello,

The assignation of @observable property not working if property != null;
```

  @observable
  Ticket? ticket;

  @action
  updateTicket(Message message) {
        // Here this.ticket != null because it's set before
        // Here this.ticket.id == message.data.id
        // Here this.ticket.updatedAt != message.data.updatedAt
        this.ticket = message.data;
        // Here this.ticket.updatedAt is always != message.data.updatedAt
        // What is this witchcraft ?
  }
```

Important note Ticket have a custom equals and hash code based uniquely on ticket.id property.

Is this the desired behaviour ?

**Comment by scipio3000** [comment]
Hello,
I'm encountering a similar problem. When I try to re-assign an observable property, it doesn't update properly. 
I also have a custom equals/hashcode set-up on an identifier.
It was fine in 2.1.3

**Comment by amondnet** [comment]
https://github.com/mobxjs/mobx.dart/blob/master/mobx/CHANGELOG.md#214
@scipio3000 @ed-oo 

Yes Prior to 2.1.4, this caused an unnecessary reaction even when the value hadn't actually changed. This was unintended behaviour.  From 2.1.4, as intended, reactions are only fired if the value has actually changed, which reduces unnecessary builds and improves performance.

https://github.com/mobxjs/mobx.dart/issues/855

```dart
@readonly
int _value;

void setValue(int value) {
  _value = value;
}
```

2.1.3
```dart
setValue(1); // reaction
setValue(1); // reaction
```

2.1.4
```dart
setValue(1); // reaction
setValue(1); // No reaction occurs
```

https://github.com/mobxjs/mobx.dart/pull/907
https://github.com/mobxjs/mobx.dart/blob/master/mobx/CHANGELOG.md#220

If you don't care about unnecessary builds and performance, use `@alwaysNotify` ( works same as previous `@observable`). 

```dart
  @alwaysNotify
  Ticket? ticket;

  @action
  updateTicket(Message message) {
        // Here this.ticket != null because it's set before
        // Here this.ticket.id == message.data.id
        // Here this.ticket.updatedAt != message.data.updatedAt
        this.ticket = message.data;
        // Here this.ticket.updatedAt is always != message.data.updatedAt
        // What is this witchcraft ?
  }
```


However, the recommended approach is 
1. `Ticket` to implement `operator ==`, so that mobx can verify that the value has actually changed.
  ```dart
  class Ticket {
    @override
    bool operator ==(Object other) =>
        identical(this, other) ||
        other is Ticket &&
            runtimeType == other.runtimeType &&
            id == other.id &&
           updatedAt == other.updatedAt;
  }
  ```
2. to use custom equals when creating observables
  ```dart
  bool customEquals(Ticket? oldValue, Ticket? newValue) => // implement ;
  @MakeObservable(equals: customEquals)
  Ticket? ticket;
  ```

3. or make `Ticket` a `store`. https://mobx.js.org/defining-data-stores.html#example-domain-store

**Comment by ed-oo** [comment]
Thank you for your time, I understand better now ! :)
